decentraland/asset-packs

- src/action-types.ts
- src/actions.ts
- src/components.ts
- src/definitions.ts
- src/index.ts
- src/scene-entrypoint.ts
- src/triggers.ts
This PR adds support for the `@dcl/asset-packs` package from VSCode. Since the `engine` use on VSCode is a different one than the one imported in this package, we needed to pass it from the parent scene, along with the pointerEventsSystem and all the components.
The types of the `initAssetPack` function are all `any` because the types would not match when used on the parent scene, because they come from different node_modules and potentially different versions of the ECS, that's why they have been all set to `any`, to avoid the parent scene having to do that conversion.
> feat: add support for vscode

- scripts/upload.ts
The `catalog.json` is not used anymore from the CDN (it is included in the npm package since it needs to be versioned), but we sitll have some outdated `catalog.json` files uploaded to the CDN, like [this one in dev](https://builder-items.decentraland.zone/catalog.json) and [this one](https://builder-items.decentraland.org/catalog.json) in prod.
This PR adds a step in the CI to remove it. Then we can remove this step from the CI.
> chore: delete catalog.json

- scripts/upload.ts
This PR is the continuation of this previous one #46 which was used to remove the now deprecated `catalog.json` from the CDN. Since that has been done, this step is now obsolete and can be removed.
> chore: remove step to delete catalog.json

- src/actions.ts
- src/definitions.ts
- src/enums.ts
This PR updates the `Set Visibility` action to set the collision mask for the `MeshRenderer/GLTF` component
Closes: https://github.com/decentraland/sdk/issues/981
> fix: Set Visibility action

- src/actions.ts
This PR fixes the video stream action to set playing a `VideoPlayer` component when it exists or create a new one using the src defined in the payload.
> fix: Play video stream action

- src/action-types.ts
This PR updates the `getActionSchema | getActionTypes` methods to use the `ActionTypes.get` instead of the `ActionTypes.getOrCreateMutable`.
Using the `getOrCreateMutable` causes an undesirable save effect in the inspector project in the DataLayer.
> fix: Gets readOnly actions instead of mutable elements

- package-lock.json
- package.json
- src/scene-entrypoint.ts
- src/triggers.ts
This PR fixes the issue where a scene deployed from VSCode would not work with smart items because the Transform component being used was not the one from the scene, but the internal one of the `@dcl/asset-packs` package.
It also added a check to avoid throwing if the entity does not have a transform (should not happen but just in case) and it upgraded the sdk to the latest version.
> fix: use correct Transform component

- src/actions.ts
- src/definitions.ts
- src/index.ts
- src/ui.ts
This PR adds the `@dcl/sdk/ecs` components: `UiTransform | UiText | UiBackground` to the`EngineComponents` type when initializing the components in scenes.
> fix: Use the correct UI transform

- packs/smart_items/assets/robot/data.json
Make the robot stop the attack loop once it dies, otherwise it messes up the explosion animation
> fix: stop attack loop when robot dies

- src/actions.ts
If the target entity is the entity itself, or a children, skip the trigger (otherwise this easily ends up in infinite loops, for example when the barrel explodes and triggers the onDamage handler of it's own health bar)
> fix: avoid triggering damage on itself of children to prevent infinite loops

- packs/smart_items/assets/fantasy_chest/data.json
- packs/smart_items/assets/fantasy_lever/data.json
- packs/smart_items/assets/video_player/data.json
- packs/smart_items/assets/wooden_door/data.json
- src/components.ts
- src/definitions.ts
- src/enums.ts
- src/triggers.ts
This PR adds a new trigger: `on_input_action`
As the entities can only have one `pointerEventsSystem.onPointerDown`, the trigger `on_click` is marked as deprecated in favor of this new trigger.
> feat: Add on input action trigger

- package-lock.json
- package.json
This PR upgrades `@dcl-sdk/utils` to `v1.2.8` which [takes into account the new avatar offset](https://github.com/decentraland/sdk7-utils/pull/16).
> fix: upgrade @dcl-sdk/utils

- .github/workflows/build-and-publish.yml
- .prettierrc.json
- packs/smart_items/assets/barrel/data.json
- packs/smart_items/assets/first_aid/data.json
- packs/smart_items/assets/healing_pad/data.json
- packs/smart_items/assets/health_bar/data.json
- packs/smart_items/assets/respawn_pad/data.json
- packs/smart_items/assets/robot/data.json
- packs/smart_items/assets/spikes/data.json
- packs/smart_items/assets/sword/data.json
- packs/smart_items/assets/wooden_wall/data.json
- src/actions.ts
- src/definitions.ts
- src/enums.ts
This PR adds the config component to the game smart items.
> feat: Add prop to actions

- packs/smart_items/assets/black_button/data.json
- packs/smart_items/assets/blue_button/data.json
- packs/smart_items/assets/blue_light_button/data.json
- packs/smart_items/assets/danger_button/data.json
- packs/smart_items/assets/green_button/data.json
- packs/smart_items/assets/green_light_button/data.json
- packs/smart_items/assets/pink_button/data.json
- packs/smart_items/assets/red_button/data.json
- packs/smart_items/assets/red_light_button/data.json
- packs/smart_items/assets/teal_button/data.json
- packs/smart_items/assets/yellow_button/data.json
- src/triggers.ts
This PR updates the default `PointerEvent` behavior for the `on_input_action` trigger, setting the button to `primary input` and the hover text to `press`.
Also, add the `PointerEvent` component to the button items.
Closes: https://github.com/decentraland/smart-items/issues/45
> feat: Use primary input action as default for pointer events

- package-lock.json
- package.json
- src/action-types.ts
- src/actions.ts
- src/clone.ts
- src/components.ts
- src/counter-bar.ts
- src/definitions.ts
- src/enums.ts
- src/events.ts
- src/id.ts
- src/index.ts
- src/input-actions.ts
- src/lww.ts
- src/scene-entrypoint.ts
- src/timer.ts
- src/transform.ts
- src/triggers.ts
- src/tweens.ts
- src/ui.ts
This PR removes a cyclic dependency between `@dcl/asset-packs` and `@dcl/sdk`, reducing the size of the package from 1.5 GB to 120 MB
BEFORE:
AFTER:
> fix: cyclic dependency

- package-lock.json
- package.json
Remove peer dependency of `@dcl/ecs` to avoid it being installed by npm when installing `@dcl/asset-packs`. This is so users can install a different version of `@dcl/sdk` and the version of `@dcl/ecs` wont clash.
> chore: remove peer dep

- src/actions.ts
- src/clone.ts
- src/components.ts
- src/definitions.ts
- src/index.ts
- src/scene-entrypoint.ts
- src/triggers.ts
Cloning a Sync Entity at runtime is not working.
The NetworkEntity component has the same values as the parent, so the other clients only sees one entity.
Also generating new entities was adding a new pointer event for each click. So you end up with a stone with N Interact pointer events.
To fix this we expose the syncEntity function to the asset-packs, and when there is a duplicate action, we call this method so the NetworkEntity has the correct values for that entity.
> fix multiplayer issue when cloning an entity at runtime

- README.md
Replace instructions for local development with Creator Hub instead of Builder
> chore: update readme with creator-hub

- src/actions.ts
This PR adds a normalization method for the animation's weight. This will ensure the animation to be executed has a valid weight between 0 and 1.
> fix: Normalize animations Weight

- src/actions.ts
This PR addresses the issue of blocked scene interactions that occur when displaying text using actions.
Fixes: https://github.com/decentraland/creator-hub/issues/272
> fix: Blocked player interactions when showing a text

- src/admin-toolkit-ui/index.tsx
The Admin Tools button needs to be moved downwards to avoid conflicting with new Explorer Debug Menu on the top right.
> chore: reposition admin tools button

- packs/smart_items/assets/vertical_platform_genesis/composite.json
This PR reverts the vertical platform basic view to the legacy one
> fix: Revert tween to basic view v1
